### ISSUE TITLE
CardView inside RycyclerView on devices < L

### ISSUE THREAD

**Issue by guguza** [ozodrukh/RippleDrawable#12]
Error occurs when I try to use your library on CardView inside RecyclerView on devices older then L, but on Lollipop devices everything is fine. Throws java.lang.ClassCastException: dreamers.graphics.RippleDrawable cannot be cast to android.support.v7.widget.RoundRectDrawableWithShadow.
What is wrong?
Thanks in advance.

**Comment by ozodrukh** [comment]
because use replaced CardViews original background, set ripple to inner view
