### ISSUE TITLE
Reverting the dev branch merge

### ISSUE THREAD

**Issue by qezt** [ozodrukh/RippleDrawable#15]
Choice 1:
Reverting a merge can be accomplished using:

http://git-scm.com/blog/2010/03/02/undoing-merges.html

Choice 2:
use `git reset "HEAD^"` on master till you reaches the stable commit, clean up, and push -f

Choice 3:

* checkout to the last stable commit, say, git check COMMIT_ID
* remove the master branch by git brand -d master
* create a master branch base on the commit, say, git checkout -b master
* push to remote: git push -u origin/master -f

All these method requires to rewrite the master header(except Choice 1 which produces a reverse commit). I haven't tried in github, but these methods work on some other remote repos. I assume they should be the same.

Good Luck.

**Comment by ozodrukh** [comment]
Thanks a lot)
