### ISSUE TITLE
<ripple> does not get overridden

### ISSUE THREAD

**Issue by BartjeNL** [ozodrukh/RippleDrawable#18]
When following instructions, when I include the library and use <ripple> in /drawable I still get the error message saying that it only works on v21+, so it gets the old one.

**Comment by ozodrukh** [comment]
well android-lint doesn't know about my library, so it will continue warn you

to remove annoying lint just add few lines of code

```xml
<ripple
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:color="@color/my_color"
    tools:ignore="NewApi" />
```
