### ISSUE TITLE
Attribute conflict with other libraries (srcCompat).

### ISSUE THREAD

**Issue by DejanRistic** [ozodrukh/RippleDrawable#22]
Would you consider prefixing custom attributes so they don't conflict with other dependencies? I'm noticing  `srcCompat` is being used in this library and a few others without any prefixing and could cause attribute already defined errors.

**Comment by AlexRyabuh** [comment]
I've the same pb. Impossible to use your solution

**Comment by waqqas-imena** [comment]
+1, If it were not for this issue, this library would be my first choice.

**Comment by dronalexandr** [comment]
Could you accept the pull request https://github.com/ozodrukh/RippleDrawable/pull/23, please ?

**Comment by asafkin** [comment]
After adding the repository and dependency to my gradle files, im still getting this srcCompat error.

**Comment by DejanRistic** [comment]
This is looking good to me on version `2.0.1`. I'm not seeing the error anymore. 

```
    compileSdkVersion 'Google Inc.:Google APIs:23'
    buildToolsVersion '24.0.0 rc2'
```
