### ISSUE TITLE
Ripple applied on listview item when scrolling

### ISSUE THREAD

**Issue by OmarBizreh** [ozodrukh/RippleDrawable#4]
I applied your library on listview item, whenever I scroll every listview item I touch while scrolling will get the ripple is applied to it. 

Thanks in advance.

**Comment by manuelpaulo** [comment]
How is this closed? I've just bought a brand new OnePlus 8 Pro and I am seeing this annoying behaviour on Facebook, Reddit, and many other apps. Even better, it's even on the listview from the phone own system settings! Blatant on dark mode. Bad implementations?
