### ISSUE TITLE
Ripple is not support oval background

### ISSUE THREAD

**Issue by IstiN** [ozodrukh/RippleDrawable#5]
If I set up background like

```
<shape
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="@color/wl_blue"/>
</shape>
```
I see "square" effect

**Comment by ozodrukh** [comment]
Yep, i did it, will upload in the week

**Comment by Saketme** [comment]
XML support is great!

**Comment by Bapho** [comment]
Transparent oval shapes or oval shapes without any background are not showing the ripple effect.. unlike rectangle shapes. Why is that?
